name: devforge-student-support-ai-agent

services:
  - name: web
    type: web
    git:
      branch: main

    build:
      builder: buildpack

    ports:
      - port: 8000
        protocol: http

    run:
      command: uvicorn main:app --host 0.0.0.0 --port 8000